# The URL the site will be built for
base_url = "https://endler.dev"

title = "Matthias Endler"
description = "Backend Engineer at trivago. Likes just-in-time compilers and hot chocolate"
generate_feed = true
feed_filename = "rss.xml"

# Go through every links in all content and check if the links are valid
check_external_links = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index out of the pages and section
# content for the `default_language`
# https://www.getzola.org/documentation/content/search/
# This is used for tinysearch
# build_search_index = true
# default_language = "en"

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

[extra]
author = "Matthias Endler"
# Enable Google analytics (comment to disable)
# id = "UA-693428-1" 
